# Site/SEO settings
email: yashaj@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Yash Khare
title: Yash's Blog
description: >
  Barber is a blog theme for Jekyll built by Thomas Vaeth for Samesies using HTML, Sass, and JavaScript.
url: https://yashk2000.github.io/blog/
twitter_username: _p0lar_bear
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/_p0lar_bear
  - name: instagram
    url: https://www.instagram.com/not_khare/
  - name: linkedin
    url: https://www.linkedin.com/in/yashk2000/
  - name: github
    url: https://github.com/yashk2000
  - name: portfolio
    url: https://yashk2000.github.io/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/Nw-OcF4l8IhW

# Disqus settings
disqus: blog-GJDk3Ow8bs

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Yash Khare
    bio: Yash is a student at Amrita Vishwa Vidyapeetham, Kerala. He is an active member of the student driven open source community of the college, amFOSS. He mainly works in the fields of Computer Vision and mobile app development.
    url: https://yashk2000.github.io/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Blog'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
