# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Yash
#comments: true

url: "https://yashk2000.github.io"
baseurl: "/myblog"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Yash's Blog

description: A blog by techie full of technical things
author:
  name: Yash Khare
  email: yashsja@gmail.com
  github: https://github.com/yashk2000
  twitter: https://twitter.com/_p0lar_bear
  linkedin: https://www.linkedin.com/in/yash-khare-b2385a178/
  bio: A techie, travel lover, open source enthusiast, guitarist!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://github.com/yashk2000/myblog/blob/gh-pages/photos/sidebar_background.jpeg

BASE_PATH:

plugins:
  - jekyll-paginate
